version: "3"

networks:
  frontend:
  backend:

services:

  nginx:
      image: registry.gitlab.com/basler/docker-nginx-fullstack-app-registry/nginx
      ports:
          - 80:80
      links:
          - backend
          - frontend
      networks:
          - frontend
          - backend

  backend:
      image: registry.gitlab.com/basler/docker-nginx-fullstack-app-registry/backend
      networks:
          - backend

  frontend:
      image: registry.gitlab.com/basler/docker-nginx-fullstack-app-registry/frontend
      networks:
          - frontend
